POST http://localhost:3001/register HTTP/1.1
content-type: application/json

{
	"username": "b",
	"password": "b"
}

POST http://localhost:3001/login HTTP/1.1
content-type: application/json

{
	"username": "a",
	"password": "b"
}